spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redisstudy
    username: study
  redis:
    host: localhost
    port: 6379

server:
  port: 8081


